### ISSUE TITLE
Assignment

### ISSUE THREAD

**Issue by leiguoyang** [leiguoyang/hello-world#6]
# Task

- [ ] issue
  - [x] open an issue
  - [x] create an issue template
  - [x] refer to another issue
  - [x] use label
  - [ ] use milestone
- [ ] pull request
  - [x] open a pull request
  - [ ] create a pull request template
  - [x] review code
- [x] fork
- [ ] contribution guidelines
- [ ] markdown
  - [x] heading
  - [x] paragraph
  - [x] ordered list 
  - [x] unordered list
  - [x] hyperlink
  - [x] insert an image
  - [x] table
  - [x] bold text
  - [x] italic text
  - [x] inline code
  - [x] block code
  - [x] ...
- [ ] add a contributor
- [ ] create an organization
- [ ] use integration & services

**Comment by leiguoyang** [comment]
# Markdown - hyperlink
This is a hyperlink. :tada:
[leiguoyang's personal website](http://leiguoyang.com)

**Comment by leiguoyang** [comment]
# Markdown - Unordered list
Things to do today:

- buy a new container
- have a hair cut
- go shopping

I just finished the first item 😆

**Comment by leiguoyang** [comment]
# Markdown - Bold Text
this is a **huge** stone.

**Comment by leiguoyang** [comment]
# Markdown - italic text
*Note: some text here*.

**Comment by leiguoyang** [comment]
# Markdown - block code
``` JavaScript
//to return the number of elements in an array
var cases = ['clientA', 'clientB', 'clientC'];
cases.length;
```

**Comment by leiguoyang** [comment]
# Markdown - ordered list
Steps to shop online

1. Search the thing you want to buy.
2. Add it to the cart.
3. Pay.
4. Wait for the delivery and enjoy.

**Comment by leiguoyang** [comment]
# Markdown - table
Functionality | Command | Example | Description
--- | --- | --- | ---
Create a new git repository | `git init` | `git init` |

**Comment by leiguoyang** [comment]
![6896282781397822825](https://cloud.githubusercontent.com/assets/15338461/21266305/8c3ac690-c3e0-11e6-9038-b2f58afef86c.jpg)

I can't get used insert an image with markdown. The `img` tag is more familiar to me. 😆

**Comment by leiguoyang** [comment]
# Bind this in a function to the targeted object

Yesterday I learnt how to use the bind function to bind the variable this in a function or method to the object I need. Here are some codes to practice how to write a block of code with Markdown.

```javascript
var me = {
  name: "leiguoyang",
  hobby: "jutar",
  printHobby: function() {
    console.log(this.name + "'s hobby is " + this.hobby);
  }
};
var you = {
  name: "unknown",
  hobby: undefined
};
me.printHobby.bind(you);
```

**Comment by leiguoyang** [comment]
[file-support.txt](https://github.com/leiguoyang/hello-world/files/687211/file-support.txt)

**Comment by leiguoyang** [comment]
This is an excel file.

[skills.xlsx](https://github.com/leiguoyang/hello-world/files/687230/skills.xlsx)

**Comment by leiguoyang** [comment]
@leiguoyang Exactly speaking, the `bind()` method is used to return a new function in which the variable this is set to the object you specified from the previous function.

**Comment by leiguoyang** [comment]
# Multiple paragraphs in a list item with Markdown

1. What is an anonymous function?

    An anonymous function is a function with no name.
2. Question 2 comes here.

    Answer here.

**Comment by leiguoyang** [comment]
# Markdown - a block code of html
```html
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Write a block cod of html</title>
  </head>
  <body>
    <p>Good night~</p>
  </body>
</html>
